name: Create Release
on:
  push:
    branches:
      - '*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read Sector File Version
        id: read_sector_version
        run: |
          SECTOR_FILE="Data/Sector/Hong-Kong-Sector-File.sct"
          SECTOR_INFO=$(grep "Hong Kong Sector" "$SECTOR_FILE")
          SECTOR_ID=$(echo $SECTOR_INFO | awk -F' ' '{print $4}')
          echo "::set-output name=SECTOR_ID::$SECTOR_ID"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.read_sector_version.outputs.SECTOR_ID }}
          tag_prefix: ""
      - name: Publish Release
        id: publish_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_sector_version.outputs.SECTOR_ID }}
          generate_release_notes: true
          draft: true
          prerelease: false
      - name: Discord Notification
        uses: LeGitHubDeTai/github-to-discord@main
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: HKvACC Helper
          # DISCORD_AVATAR: https://raw.githubusercontent.com/LeGitHubDeTai/github-to-discord/main/icon.png
          MESSAGE_TITLE: Sector File Update ${{ steps.read_sector_version.outputs.SECTOR_ID }} Now Available!
          MESSAGE_DESCRIPTION: <@&1117123659027464193> All controllers should update using the Hong Kong Sector Installer.
          MESSAGE_URL: ${{ steps.publish_release.outputs.upload_url }}
          MESSAGE_COLOR: 5814783
