name: Create Release
on:
  push:
    branches:
      - '*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read Sector File Version
        id: read_sector_version
        run: |
          SECTOR_FILE="Data/Sector/Hong-Kong-Sector-File.sct" 
          SECTOR_INFO=$(grep "Hong Kong Sector" "$SECTOR_FILE")
          SECTOR_ID=$(echo $SECTOR_INFO | awk -F' ' '{print $4}')
          echo "::set-output name=SECTOR_ID::$SECTOR_ID"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.read_sector_version.outputs.SECTOR_ID }}
          tag_prefix: ""
      - name: Publish Release Draft
        id: publish_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_sector_version.outputs.SECTOR_ID }}
          generate_release_notes: true
          draft: true
          prerelease: false
  
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        with:
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Discord Update Ping
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '{"embeds":[{"title":"Sector Package ${{ steps.get_current_release.outputs.tag_name }} Released ","url":"${{ steps.get_current_release.outputs.url }}","color":"2393011","description":"An update to the Hong Kong Sector Package is now available. All controllers should update using the installer."}]}'
        uses: Ilshidur/action-discord@master
